# Generated by Django 2.0.4 on 2018-04-25 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('edited_on', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='editwiki',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='editwiki',
            name='wiki',
        ),
        migrations.RenameField(
            model_name='wiki',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='wiki',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='wiki',
            old_name='is_published',
            new_name='published',
        ),
        migrations.DeleteModel(
            name='EditWiki',
        ),
        migrations.AddField(
            model_name='revision',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Wiki'),
        ),
    ]
