# Generated by Django 2.0.4 on 2018-04-25 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_auto_20180425_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Wiki')),
            ],
        ),
        migrations.RemoveField(
            model_name='revision',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='wiki',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
