# Generated by Django 2.0.4 on 2018-04-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180425_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='author',
        ),
        migrations.RemoveField(
            model_name='add',
            name='wiki',
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
